[project]
name = "hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "google>=3.0.0",
    "google-genai>=1.41.0",
    "requests>=2.32.5",
]
